### ISSUE TITLE
Need a team onboarding document

### ISSUE THREAD

**Issue by paulopperman** [NewportDataProject/docs#1]
Document that talks about the overall project structure, what the high level expectations are, where we have conversations, and some of the tools to get started.

**Comment by paulopperman** [comment]
draft posted in slack: https://newportdataproject.slack.com/files/U3LFJUKKR/F709KCCD7/introduction.md

**Comment by thescientist13** [comment]
This looks good @paulopperman !

Is your plan to use the wiki feature of GitHub (against this repo) or the website?

**Comment by paulopperman** [comment]
(risking repeating conversation in the slack channel) My thoughts were to use the repo itself to host the documentation. Content would be tracked via git, and we can leverage github pages and jekyll to serve up a clean readable version at the `/docs` path of the website.
